#! /bin/sh
# (c) Copyright 2019-2020, James Stevens ... see LICENSE for details
# Alternative license arrangements are possible, contact me for more information

export PATH=$PATH:/opt/python/bin
export DOH_SERVERS=127.0.0.1

cd /usr/local/dns
exec gunicorn --bind unix:/run/dnsflsk_$1.sock wsgi
